### ISSUE TITLE
关于算法1的表？

### ISSUE THREAD

**Issue by jjb202** [hongwang01/VRGNet#2]
你好，你的论文很棒！然后我有点问题，就是在用prenet网络得到的均值方差后，你论文中算法1表中写了一步b的更新需要再Reparameterization（期望，方差），但是我在syn_joint代码中似乎没找到这一步骤。请问是调用在了哪个位置？

**Comment by hongwang01** [comment]
谢谢对我们工作的关注！

https://github.com/hongwang01/VRGNet/blob/834c2c64be363797fe3741f4f8e8d17657f9b614/for_syn/vrgnet.py#L50

**Comment by jjb202** [comment]
你好，这个应该是生成隐变量z网络RNet的。我未找到BNet的

**Comment by hongwang01** [comment]
> 


> 你好，这个应该是生成隐变量z网络RNet的。我未找到BNet的

对的。在代码实现里，RNet做了重参数化为了进行梯度回传，BNet是有监督的，我们直接利用学习到的均值作为采样输出。

**Comment by jjb202** [comment]
谢谢，我看到算法1表出现了两个参数化，就有点不解。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Hong Wang ***@***.***&gt;
发送时间: 2021年12月27日 17:49
收件人: hongwang01/VRGNet ***@***.***&gt;
抄送: hello ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [hongwang01/VRGNet] 关于算法1的表？ (Issue #2)

**Comment by hongwang01** [comment]
> 谢谢，我看到算法1表出现了两个参数化，就有点不解。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Hong Wang ***@***.***&gt; 发送时间: 2021年12月27日 17:49 收件人: hongwang01/VRGNet ***@***.***&gt; 抄送: hello ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [hongwang01/VRGNet] 关于算法1的表？ (Issue #2)

明白，你看的很仔细，我们在实现这一步的时候的确简化了。
